server:
  port: 8083
spring:
  datasource:
    driverClassName: org.h2.Driver
    password: password
    url: jdbc:h2:mem:testdb
    username: sa
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  
  rabbitmq:
    request:
      host: localhost
      port: 5672
      username: guest
      password: guest
      exchange:
        producer: ex.producer.boleto
      routing-key:
        producer: rk.producer.boleto
      dead-letter:
        producer: dl.producer.boleto
      parking-lot:
        producer: pl.producer.boleto
